Дополнил примеры в README
Arity-T/1_quaternions pull request #5
Opened 2024-11-06 21:54 UTC by DmitriyGubkovskiy

2024-11-06 21:55 UTC, DmitriyGubkovskiy commented
Также имею вопрос. У нас существует метод normalized. Очень важный метод. Для него нет тестов. Думаю, нужно сделать.

2024-11-07 08:18 UTC, Arity-T requested changes
Зачем ты разбил на кучу блоков с кодом, и в каждом дублируешь код для импорта и код для создания кватернионов? Просто сделай один блок и в нём несколько принтов. Кстати, в примерах хорошо бы добавить результат выполнения кода, но только отдельным блоком кода.
Как-нибудь так

```python
print(10 + 20)
print(20 + 20)
print(10 * 10)
```
```
30
40
100
```

2024-11-07 08:18 UTC, Arity-T commented on README.md
> +print(a + b)
Не похоже на вычитание

2024-11-07 18:26 UTC, Arity-T approved these changes

2024-11-11 23:11 UTC, merged